I'm sorry, but an uncaught exception occurred.

While loading <renpy.display.im.Image object ('images/ep5/characters/gyeoul_call.png') at 0x1023e8880>:
  File "game/EP5.rpy", line 215, in script
    gyeoul "너 생각보다 쓸모 있는 것 같으니 같이 해도 좋겠다고!!"
OSError: Couldn't find file 'images/ep5/characters/gyeoul_call.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/EP5.rpy", line 215, in script
    gyeoul "너 생각보다 쓸모 있는 것 같으니 같이 해도 좋겠다고!!"
  File "/Applications/renpy-8.2.1-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/Applications/renpy-8.2.1-sdk/renpy/ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-8.2.1-sdk/renpy/exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "/Applications/renpy-8.2.1-sdk/renpy/character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/Applications/renpy-8.2.1-sdk/renpy/character.py", line 1045, in do_display
    display_say(who,
  File "/Applications/renpy-8.2.1-sdk/renpy/character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Applications/renpy-8.2.1-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-8.2.1-sdk/renpy/display/core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Applications/renpy-8.2.1-sdk/renpy/display/core.py", line 2818, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "/Applications/renpy-8.2.1-sdk/renpy/display/core.py", line 1352, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 486, in renpy.display.render.render_screen
  File "render.pyx", line 260, in renpy.display.render.render
  File "/Applications/renpy-8.2.1-sdk/renpy/display/layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "/Applications/renpy-8.2.1-sdk/renpy/display/layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "/Applications/renpy-8.2.1-sdk/renpy/display/layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "/Applications/renpy-8.2.1-sdk/renpy/display/transform.py", line 957, in render
    return RenderTransform(self).render(width, height, st, at)
  File "accelerator.pyx", line 978, in renpy.display.accelerator.RenderTransform.render
  File "accelerator.pyx", line 413, in renpy.display.accelerator.RenderTransform.render_child
  File "render.pyx", line 260, in renpy.display.render.render
  File "/Applications/renpy-8.2.1-sdk/renpy/display/image.py", line 513, in render
    return wrap_render(self.target, width, height, st, at)
  File "/Applications/renpy-8.2.1-sdk/renpy/display/image.py", line 316, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "/Applications/renpy-8.2.1-sdk/renpy/display/im.py", line 626, in render
    return cache.get(self, render=True)
  File "/Applications/renpy-8.2.1-sdk/renpy/display/im.py", line 309, in get
    surf = image.load()
  File "/Applications/renpy-8.2.1-sdk/renpy/display/im.py", line 761, in load
    raise e
  File "/Applications/renpy-8.2.1-sdk/renpy/display/im.py", line 711, in load
    filelike = renpy.loader.load(self.filename, directory="images")
  File "/Applications/renpy-8.2.1-sdk/renpy/loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'images/ep5/characters/gyeoul_call.png'.

macOS-14.4-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
ep4 1.0
Mon Apr  8 05:28:29 2024
